### ISSUE TITLE
Change master branch to main

### ISSUE THREAD

**Issue by thom-at-redhat** [redhat-performance/opl#3]
As part of conscious language project, please change the default branch from 'master' to 'main'

**Comment by pablomh** [comment]
The `main` branch is now there and the only missing bit would be to switch the default one to it.

**Comment by pablomh** [comment]
Done. @jhutar will send an email to the interested parties so they're aware.

**Comment by jhutar** [comment]
Nice!

**Comment by pablomh** [comment]
I've also implemented the same "Branch protection rules" to the new default branch.
